### ISSUE TITLE
Nesting with tree-traversal

### ISSUE THREAD

**Issue by digikar99** [Harleqin/arrows#1]
I don't think I quite understand the difference between a code-walker and [a simple tree-traversal](https://github.com/digikar99/simple-arrows/blob/2e86f6aa3cbbe62fc0ca2af49e0b04be49de51e8/simple-arrows.lisp#L23). What cases does the former catch that the latter misses, in case of something like `-<>`?

**Comment by digikar99** [comment]
Okay, found a failing test-case:

```lisp
(-<> 5
  (+ 6 <>
     (eval (macroexpand `(-<> 10
                           (+ 2 <> ,<>))))))
```

Also [this discussion on rplevy/swiss-arrows](https://github.com/rplevy/swiss-arrows/issues/22). Even arrow-macros fails this test case with a code-walker though. And it (arrow-macros) also fails 

```lisp
(as-> 5 a
      (+ 6 a
         (eval (macroexpand `(as-> 10 a
                                   (+ 2 a ,a))))))
;=> 28
```

**Comment by digikar99** [comment]
[Fixed this one](https://github.com/digikar99/simple-arrows/blob/8b335f2dcb0a7b247bf5911d904b717161527490/simple-arrows.lisp#L22) using an approach similar to `as->`, directly bind the symbol `<>` itself. Again, don't understand the limitation with this approach.

**Comment by Harleqin** [comment]
I may not entirely have understood your point, but I do not see where you address the question what happens if a subform does not have the `<>` placeholder.

**Comment by Harleqin** [comment]
Test case: `(-<> 3 (/ 2))`
